name: opentoken_app
description: Official OpenToken Sovereign Authenticator
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_nfc_kit: ^3.4.2
  provider: ^6.0.5
  crypto: ^3.0.3
  google_fonts: ^6.1.0
  flutter_blurhash: ^0.8.2
  base32: ^2.1.3
  opentoken_dart:
    path: c:/OpenToken/libraries/opentoken-dart

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
