name: opentoken_dart
description: Official Shared Dart SDK for OpenToken (Mobile & Desktop)
version: 1.0.0
homepage: https://github.com/zequinha-taveira/OpenToken

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta: ^1.11.0
  crypto: ^3.0.3
  ffi: ^2.1.2
  win32: ^5.2.0
  cbor: ^6.1.1
